const foods = [
  {
    id: 1,
    name: "Rolex",
    category: "street",
    desc: "Uganda's beloved street food – a fresh chapati rolled with fried eggs, cabbage, tomatoes and onions. Crispy, filling, and absolutely delicious.",
    time: "15 min",
    difficulty: "easy",
    rating: 4.9,
    reviews: 1240,
    img: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80",
    tags: ["street", "breakfast", "quick"],
    calories: 380,
    protein: "14g",
    carbs: "52g",
    fat: "12g",
  },
  {
    id: 2,
    name: "Luwombo",
    category: "traditional",
    desc: "A royal Buganda dish – tender chicken or beef steamed in banana leaves with groundnut sauce, creating an aromatic and deeply flavourful stew.",
    time: "2 hrs",
    difficulty: "hard",
    rating: 4.8,
    reviews: 890,
    img: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80",
    tags: ["traditional", "special"],
    calories: 520,
    protein: "38g",
    carbs: "18g",
    fat: "32g",
  },
  {
    id: 3,
    name: "Matoke",
    category: "traditional",
    desc: "Steamed green bananas cooked to tender perfection in banana leaves. A Ugandan staple served with groundnut sauce, meat stew or beans.",
    time: "45 min",
    difficulty: "medium",
    rating: 4.7,
    reviews: 1120,
    img: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80",
    tags: ["traditional", "vegetarian"],
    calories: 290,
    protein: "3g",
    carbs: "70g",
    fat: "1g",
  },
  {
    id: 4,
    name: "Posho & Beans",
    category: "traditional",
    desc: "The ultimate Ugandan comfort food – thick white maize porridge paired with rich, slow-cooked kidney beans. Humble, hearty and nourishing.",
    time: "30 min",
    difficulty: "easy",
    rating: 4.6,
    reviews: 2100,
    img: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80",
    tags: ["traditional", "vegetarian", "quick"],
    calories: 410,
    protein: "18g",
    carbs: "75g",
    fat: "3g",
  },
  {
    id: 5,
    name: "Groundnut Sauce",
    category: "traditional",
    desc: "A rich, creamy peanut-based sauce simmered with tomatoes, onions and spices. The soul of Ugandan cuisine, served over everything.",
    time: "35 min",
    difficulty: "medium",
    rating: 4.8,
    reviews: 980,
    img: "https://images.unsplash.com/photo-1476224203421-74177e9807a6?auto=format&fit=crop&w=600&q=80",
    tags: ["traditional", "vegetarian"],
    calories: 340,
    protein: "12g",
    carbs: "22g",
    fat: "24g",
  },
  {
    id: 6,
    name: "Pilau",
    category: "traditional",
    desc: "Fragrant, spiced rice cooked with pilau masala, tender beef and caramelized onions. A festive Ugandan rice dish full of warm aromatic spices.",
    time: "1 hr",
    difficulty: "medium",
    rating: 4.9,
    reviews: 1560,
    img: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=600&q=80",
    tags: ["traditional", "special"],
    calories: 580,
    protein: "28g",
    carbs: "68g",
    fat: "18g",
  },
  {
    id: 7,
    name: "Chapati",
    category: "breakfast",
    desc: "Soft, flaky layered flatbread cooked on a hot griddle. A Ugandan breakfast staple enjoyed with beans, stew or wrapped into a delicious Rolex.",
    time: "30 min",
    difficulty: "medium",
    rating: 4.7,
    reviews: 1890,
    img: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80",
    tags: ["breakfast", "street", "vegetarian"],
    calories: 280,
    protein: "7g",
    carbs: "48g",
    fat: "8g",
  },
  {
    id: 8,
    name: "Muchomo",
    category: "street",
    desc: "Succulent goat or beef skewers grilled over charcoal fire with a smoky spice rub. Uganda's favourite street-corner grilled meat experience.",
    time: "40 min",
    difficulty: "medium",
    rating: 4.9,
    reviews: 2340,
    img: "https://images.unsplash.com/photo-1544025162-d76538891a23?auto=format&fit=crop&w=600&q=80",
    tags: ["street", "special"],
    calories: 460,
    protein: "42g",
    carbs: "4g",
    fat: "28g",
  },
  {
    id: 9,
    name: "Katogo",
    category: "breakfast",
    desc: "A hearty one-pot breakfast of matooke or offal cooked with groundnuts or beans. A warming, robust start to any Ugandan morning.",
    time: "45 min",
    difficulty: "medium",
    rating: 4.5,
    reviews: 640,
    img: "https://images.unsplash.com/photo-1539755530862-00f623c00f52?auto=format&fit=crop&w=600&q=80",
    tags: ["breakfast", "traditional"],
    calories: 390,
    protein: "22g",
    carbs: "40g",
    fat: "14g",
  },
  {
    id: 10,
    name: "Mandazi",
    category: "snack",
    desc: "Light, fluffy East African doughnuts with a hint of cardamom and coconut. Perfect with chai tea for a delightful Ugandan afternoon snack.",
    time: "25 min",
    difficulty: "easy",
    rating: 4.6,
    reviews: 780,
    img: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
    tags: ["snack", "breakfast", "quick"],
    calories: 220,
    protein: "5g",
    carbs: "38g",
    fat: "7g",
  },
  {
    id: 11,
    name: "Nsenene",
    category: "snack",
    desc: "Fried grasshoppers seasoned with onions, garlic and chilli. A seasonal Ugandan delicacy that is crunchy, savoury and surprisingly addictive.",
    time: "20 min",
    difficulty: "easy",
    rating: 4.4,
    reviews: 420,
    img: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=600&q=80",
    tags: ["snack", "traditional"],
    calories: 180,
    protein: "16g",
    carbs: "6g",
    fat: "10g",
  },
  {
    id: 12,
    name: "Kikomando",
    category: "street",
    desc: "Chapati cut into bite-sized pieces mixed with kidney beans. A budget-friendly, filling Ugandan street food loved by students and workers alike.",
    time: "20 min",
    difficulty: "easy",
    rating: 4.5,
    reviews: 1100,
    img: "https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=600&q=80",
    tags: ["street", "quick", "vegetarian"],
    calories: 320,
    protein: "14g",
    carbs: "58g",
    fat: "6g",
  },
];
